name: CI with Email Notification.

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run tests and capture logs + summary
        run: |
          echo "Running tests..."
          # Save complete logs
          npm test > logs.txt 2>&1 || true
          
          # Extract test summary (works with Jest/Mocha)
          grep -E "Tests:|Passing|Failing|Total|passed|failed" logs.txt > summary.txt || echo "No summary found" > summary.txt

      - name: Show captured summary
        run: cat summary.txt

      - name: Send detailed email via SendGrid
        if: always() # send email even if tests fail
        uses: licenseware/send-email-notification@v1
        with:
          api-key: ${{ secrets.SENDGRID_API_KEY }}
          subject: "Workflow ${{ github.workflow }} – ${{ job.status }}"
          from-email: raghavk15@outlook.com
          to-email: your-email@example.com
          markdown-body: |
            ## 🚀 GitHub Actions Report
            **Repository:** ${{ github.repository }}
            **Workflow:** ${{ github.workflow }}
            **Job:** ${{ github.job }}
            **Status:** ${{ job.status }}
            **Run Link:** [View Logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

            ### ✅ Test Summary
            ```text
            $(cat summary.txt)
            ```

            ### 📄 Logs (first 30 lines)
            ```text
            $(head -n 30 logs.txt)
            ```
          attachments: |
            logs.txt
            summary.txt
          attachments-disposition: attachment
